---
#
- name: CONFIG L3 EDGE VLAN
  any_errors_fatal: true
  cisco.ios.ios_config:
    lines:
      - "vlan {{ edge_vlan_id }}"
      - " name {{ edge_vlan_id }}"
#
- name: CONFIG L3 SVI INTERFACE EDGE VLAN
  any_errors_fatal: true
  cisco.ios.ios_config:
    lines:
      - "interface Vlan{{ edge_vlan_id }}"
      - " description {{ edge_vlan_id }} SVI-INTERFACE"
      - " vrf forwarding {{ vrf_name }}"
      - " ip address {{ ip_address }} {{ ip_mask }}"
      - " ipv6 address {{ ipv6_address }}/{{ ipv6_prefix }}"
      - " ip dhcp relay information option vpn-id"
      - " ip helper-address global {{ primary_dhcp_server }}"
      - no shutdown
#
- name: SHOW CONFIG
  any_errors_fatal: true
  cisco.ios.ios_command:
    commands:
      - "show running-config | section vlan {{ edge_vlan_id }}"
      - "show running-config interface Vlan{{ edge_vlan_id }}"
  register: after_show_config
#
- name: DEBUG
  ansible.builtin.debug:
    msg:
      - "{{ after_show_config.stdout_lines }}"
#
...