---
#
- name: CONFIG NVE INTERFACE INGRESS REPL
  any_errors_fatal: true
  cisco.ios.ios_config:
    lines:
      - "interface nve {{ nve_id }}"
      - description VXLAN AGGREGATION INTERFACE
      - no ip address
      - " source-interface {{ loopback }}"
      - " host-reachability protocol bgp"
      - " member vni {{ l3_vni_id }} vrf {{ vrf_name }}"
      - " member vni {{ l2vni_instance_id }} ingress-replication"
#
- name: SHOW CONFIG
  any_errors_fatal: true
  cisco.ios.ios_command:
    commands:
      - "show running-config interface nve {{ nve_id }}"
  register: after_show_config
#
- name: DEBUG
  ansible.builtin.debug:
    msg:
      - "{{ after_show_config.stdout_lines }}"
#
...