---
#
- hosts: network
  gather_facts: no
#
  tasks:
#
    - name: CLEAR CONFIG BGP IPV4 SPINE
      cisco.ios.ios_config:
        lines:
          - "no router bgp {{ bgp_asn }}"
      failed_when: false
#
    - name: CLEAR CONFIG BGP LEAF BORDER HANDOFF
      cisco.ios.ios_config:
        lines:
          - "no router bgp {{ bgp_asn }}"
      failed_when: false
#
    - name: CLEAR CONFIG BGP IPV4 LEAF
      cisco.ios.ios_config:
        lines:
          - "no router bgp {{ bgp_asn }}"
      failed_when: false
#
    - name: CLEAR CONFIG NVE INTERFACE MCAST REPL
      cisco.ios.ios_config:
        lines:
          - "no interface nve {{ nve_id }}"
      failed_when: false
#
    - name: CLEAR CONFIG NVE INTERFACE INGRESS REPL
      cisco.ios.ios_config:
        lines:
          - "no interface nve {{ nve_id }}"
      failed_when: false
#
    - name: CLEAR CONFIG NVE INTERFACE
      cisco.ios.ios_config:
        lines:
          - "no interface nve {{ nve_id }}"
      failed_when: false
#
    - name: CLEAR CONFIG DHCP GLOBAL
      cisco.ios.ios_config:
        lines:
          - no ip dhcp relay information option vpn
          - no ip dhcp relay information option
          - no ip dhcp compatibility suboption link-selection standard
          - no ip dhcp compatibility suboption server-override standard
      failed_when: false
#
    - name: CLEAR CONFIG LEAF_CORE_VLAN_IPV4
      cisco.ios.ios_config:
        lines:
          - "no vlan configuration {{ core_vlan_id }}"
          - "no vlan {{ core_vlan_id }}"
          - "no interface Vlan{{ core_vlan_id }}"
      failed_when: false
#
    - name: CLEAR CONFIG DHCP L2VNI L3 EDGE VLAN INTERFACE SVI
      cisco.ios.ios_config:
        lines:
          - "no interface Vlan{{ l2vni_edge_vlan_id }}"
      failed_when: false
#
    - name: CLEAR CONFIG L2VNI_CONFIG_IPV4 1
      cisco.ios.ios_config:
        lines:
          - "no interface Vlan{{ l2vni_edge_vlan_id }}"
      failed_when: false
#
    - name: CLEAR CONFIG L2VNI_CONFIG_IPV4 2
      cisco.ios.ios_config:
        lines:
          - "no l2vpn evpn instance {{ l2vni_instance_id }} vlan-based"
          - "no vlan configuration {{ l2vni_edge_vlan_id }}"
          - "no vlan {{ l2vni_edge_vlan_id }}"
      failed_when: false
#
    - name: CLEAR CONFIG L2VPN EVPN REPLICATION MODE
      cisco.ios.ios_config:
        lines:
          - no l2vpn evpn
      failed_when: false
#
    - name: CLEAR CONFIG VRF IPV4
      cisco.ios.ios_config:
        lines:
          - "no vrf definition {{ vrf_name }}"
      failed_when: false
#
    - name: SHOW VRF
      cisco.ios.ios_command:
        commands:
          - show vrf
        wait_for:
          "result[0] not contains {{ vrf_name }}"
        retries: 999
      register: after_show_vrf
#
...