---
#
leafs:
#
  hosts:
#
    sw-access-leaf-1:
      ansible_host: 10.1.3.15
      role: leaf
      rid: 10.255.255.253
      ip_address: 10.252.255.1
      ip_mask: 255.255.255.0
      ipv6_address: 2001:0:0:0:DB8:800:200C:528b
      ipv6_prefix: 48
      dag_mac: 0012.3456.7890
      dag_ipv4_address: 10.251.255.1
      dag_ipv4_mask: 255.255.255.0
      dag_ipv6_address: 2002:0:0:0:EC9:911:311D:639C
      dag_ipv6_prefix: 48
#
    sw-access-leaf-2:
      ansible_host: 10.1.3.7
      role: border
      rid: 10.255.255.252
      ip_address: 10.252.255.2
      ip_mask: 255.255.255.0
      ipv6_address: 2001:0:0:0:DB8:800:200C:417A
      ipv6_prefix: 48
      dag_mac: 0011.2233.4455
      dag_ipv4_address: 10.251.255.2
      dag_ipv4_mask: 255.255.255.0
      dag_ipv6_address: 2002:0:0:0:EC9:911:311D:528B
      dag_ipv6_prefix: 48
#
  vars:
#
spines:
#
  hosts:
#
    sw-core-spine-1:
      ansible_host: 10.1.3.6
      rid: 10.255.255.254
#
  vars:
#
network:
#
  children:
#
    leafs:
#
    spines:
#
  vars:
    backups_path: ./backup/
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_user: tmelab
    ansible_password: Uab00tcamp!
    ansible_become: no
    ansible_become_method: enable
    ansible_become_password: Uab00tcamp!
    ping_count: 1000
    ping_loss: 10
    vrf_name: VRF_OVERLAY_2010
    bgp_asn: 64512
    remote_as: 64512
    core_vlan_id: 2010
    l3_vni_id: 20010
    edge_vlan_id: 2020
    primary_dhcp_server: 10.10.10.10
    secondary_dhcp_server: 10.20.20.20
    nve_id: 1
    border_ip: 10.9.8.7
    border_remote_as: 64513
    loopback: Loopback1
    bgp_source: Loopback0
    l2vpn_evpn_repl_type: ingress
    l2vni_mcast_grp: 225.4.5.6
    l2vni_edge_vlan_id: 2030
    l2vni_instance_id: 20030
#
...