---
#
- name: CONFIG L2VPN EVPN REPLICATION MODE
  any_errors_fatal: true
  cisco.ios.ios_config:
    lines:
      - l2vpn evpn
      - " replication-type {{ l2vpn_evpn_repl_type }}"
#
- name: SHOW CONFIG
  any_errors_fatal: true
  cisco.ios.ios_command:
    commands:
      - "show running-config | section l2vpn evpn"
      - "show running-config | section replication-type"
  register: after_show_config
#
- name: DEBUG
  ansible.builtin.debug:
    msg:
      - "{{ after_show_config.stdout_lines }}"
#
...