---
#
- name: CONFIG DHCP GLOBAL
  any_errors_fatal: true
  cisco.ios.ios_config:
    lines:
      - ip dhcp relay information option vpn
      - ip dhcp relay information option
      - ip dhcp compatibility suboption link-selection standard
      - ip dhcp compatibility suboption server-override standard
#
- name: SHOW CONFIG
  any_errors_fatal: true
  cisco.ios.ios_command:
    commands:
      - "show running-config | section ip dhcp relay information option vpn"
      - "show running-config | section ip dhcp relay information option"
      - "show running-config | section ip dhcp compatibility suboption link-selection standard"
      - "show running-config | section ip dhcp compatibility suboption server-override standard"
  register: after_show_config
#
- name: DEBUG
  ansible.builtin.debug:
    msg:
      - "{{ after_show_config.stdout_lines }}"
#
...