---
#
- name: SHOW LICENSE SUMMARY
  any_errors_fatal: true
  cisco.ios.ios_command:
    commands:
      - show license summary
  register: after_show_license
#
- name: ASSERT SUCCESS OR FAILURE BASED ON LICENSE TYPE
  any_errors_fatal: true
  assert:
    that:
      - after_show_license.stdout is search('network-advantage')
    fail_msg: "---> Device does not meet license requirement to enable EVPN <---"
    success_msg: "---> Device meet license requirement to enable EVPN <---"
#
- name: DEBUG
  ansible.builtin.debug:
    msg:
      - "{{ after_show_license }}"
#
...