---
#
# 1
- import_tasks: roles/common/tasks/verification_license.yml
# 2
- import_tasks: roles/common/tasks/verification_leafs_to_spines.yml
  when: "'leafs' in group_names"
# 3
- import_tasks: roles/common/tasks/verification_spines_to_leafs.yml
  when: "'spines' in group_names"
# 4
- import_tasks: roles/common/tasks/backup_config.yml
# 5
- include_tasks: leaf_core_vrf_ipv4.yml
  when: "'leafs' in group_names"
# 6
- include_tasks: repl_mode.yml
  when: "'leafs' in group_names"
# 7
- include_tasks: l2vni_config_ipv4.yml
  when: "'leafs' in group_names"
# 8
- include_tasks: l2vni_dhcp_config.yml
  when: "'leafs' in group_names"
# 9
- include_tasks: leaf_core_vlan_ipv4.yml
  when: "'leafs' in group_names"
# 10
- include_tasks: dhcp_config.yml
  when: "'leafs' in group_names"
# 11
- include_tasks: nve_interface.yml
  when: "'leafs' in group_names"
# 12
- include_tasks: nve_interface_ingress_repl.yml
  when: "'ingress' in l2vpn_evpn_repl_type and 'leafs' in group_names"
# 13
- include_tasks: nve_interface_mcast_repl.yml
  when: "'static' in l2vpn_evpn_repl_type and 'leafs' in group_names"
# 14
- include_tasks: bgp_config_ipv4.yml
  when: "'leafs' in group_names"
# 15
- include_tasks: leaf_border_handoff.yml
  when: "'leafs' in group_names and 'border' in role"
# 16
- include_tasks: spine_bgp_ipv4_core.yml
  when: "'spines' in group_names"
# 17
- import_tasks: roles/common/tasks/save_config.yml
# 18
- import_tasks: roles/common/tasks/backup_config.yml
# 19
- include_tasks: roles/common/tasks/verification_bgp.yml
  when: "'spines' in group_names"
#
...