---
#
- name: SAVE CONFIG
  any_errors_fatal: true
  cisco.ios.ios_command:
    commands:
      - write memory
  register: after_save_config
#
- name: DEBUG
  ansible.builtin.debug:
    msg:
      - "{{ after_save_config.stdout_lines }}"
#
...