---
#
- name: SHOW IP BGP L2VPN EVPN SUMMARY
  any_errors_fatal: true
  cisco.ios.ios_command:
    commands:
      - "show ip bgp l2vpn evpn summary | begin Up/Down"
  register: after_show_bgp
#
- name: DEBUG
  ansible.builtin.debug:
    msg:
      - "{{ after_show_bgp }}"
#
- name: "ASSERT SUCCESS OR FAILURE BASED ON BGP OUTPUT: UPTIME > 00:00:00 OR NOT NEVER AND NEIGHBOORS LEAFS LISTED CORRECTLY"
  any_errors_fatal: true
  assert:
    that:
      - after_show_bgp.stdout is search('{{ hostvars[item].rid }}')
      - after_show_bgp.stdout is not search('00:00:00')
      - after_show_bgp.stdout is not search('never')
    fail_msg: "---> BGP SESSIONS NOT ESTABLISHED! <---"
    success_msg: "---> BGP SESSIONS ESTABLISHED! <---"
    quiet: no
  with_items:
    - "{{ groups['leafs'] }}"
  register: after_assert
#
- name: DEBUG
  ansible.builtin.debug:
    msg:
      - "{{ after_assert }}"
#
...