---
#
- name: CONFIG VTP MODE
  any_errors_fatal: true
  cisco.ios.ios_config:
    lines:
      - vtp mode transparent
#
- name: CONFIG L2 CORE VLAN
  any_errors_fatal: true
  cisco.ios.ios_config:
    lines:
      - "vlan {{ core_vlan_id }}"
      - " name {{ core_vlan_id }}"
#
- name: CONFIG L2 CORE VLAN MEMBER L3 VNI CONFIGURATION
  any_errors_fatal: true
  cisco.ios.ios_config:
    lines:
      - "vlan configuration {{ core_vlan_id }}"
      - " member vni {{ l3_vni_id }}"
#
- name: CONFIG L3 SVI CORE VLAN INTERFACE
  any_errors_fatal: true
  cisco.ios.ios_config:
    lines:
      - "interface Vlan{{ core_vlan_id }}"
      - " description {{ core_vlan_id }} SVI Interface"
      - " vrf forwarding {{ vrf_name }}"
      - " ip unnumbered {{ loopback }}"
      - no autostate
      - no shutdown
#
- name: SHOW CONFIG
  any_errors_fatal: true
  cisco.ios.ios_command:
    commands:
      - "show running-config | section vtp mode transparent"
      - "show running-config | section vlan {{ core_vlan_id }}"
      - "show running-config | section vlan configuration {{ core_vlan_id }}"
      - "show running-config interface Vlan{{ core_vlan_id }}"
  register: after_show_config
#
- name: DEBUG
  ansible.builtin.debug:
    msg:
      - "{{ after_show_config.stdout_lines }}"
#
...
