---
#
- name: CONFIG MULTICAST GLOBAL
  any_errors_fatal: true
  cisco.ios.ios_config:
    lines:
      - "ip multicast-routing vrf {{ vrf_name }}"
      - "ip pim vrf {{ vrf_name }} rp-address {{ anycast_rp }}"
#
- name: SHOW CONFIG
  any_errors_fatal: true
  cisco.ios.ios_command:
    commands:
      - "show running-config | section ip multicast-routing vrf {{ vrf_name }}"
      - "show running-config | section ip pim vrf {{ vrf_name }} rp-address {{ anycast_rp }}"
  register: after_show_config
#
- name: DEBUG
  ansible.builtin.debug:
    msg:
      - "{{ after_show_config.stdout_lines }}"
#
...