---
#
- name: CONFIG NVE INTERFACE
  any_errors_fatal: true
  tags:
    - add_nve
    - day_two
  cisco.ios.ios_config:
    lines:
      - "interface nve {{ nve_id }}"
      - description VXLAN AGGREGATION INTERFACE
      - no ip address
      - " source-interface {{ loopback }}"
      - " host-reachability protocol bgp"
      - " member vni {{ item.vrf_l3_vni_id }} vrf {{ item.vrf_name }}"
  with_items: "{{ vrfs }}"
#
- name: SHOW CONFIG
  any_errors_fatal: true
  tags:
    - add_nve
    - day_two
  cisco.ios.ios_command:
    commands:
      - "show running-config interface nve {{ nve_id }}"
  register: after_show_config
#
- name: DEBUG
  tags:
    - add_nve
    - day_two
  ansible.builtin.debug:
    msg:
      - "{{ after_show_config.stdout_lines }}"
#
...