---
#
- hosts: network
  gather_facts: no
#
  tasks:
#
    - name: CLEAR CONFIG BGP IPV4 SPINE
      cisco.ios.ios_config:
        lines:
          - "no router bgp {{ bgp_asn }}"
      failed_when: false
#
    - name: CLEAR CONFIG BGP LEAF BORDER HANDOFF
      cisco.ios.ios_config:
        lines:
          - "no router bgp {{ bgp_asn }}"
      failed_when: false
#
    - name: CLEAR CONFIG BGP LEAF
      cisco.ios.ios_config:
        lines:
          - "no router bgp {{ bgp_asn }}"
      failed_when: false
#
    - name: CLEAR CONFIG NVE INTERFACE
      cisco.ios.ios_config:
        lines:
          - "no interface nve {{ nve_id }}"
      failed_when: false
#
    - name: CLEAR CONFIG DHCP GLOBAL
      cisco.ios.ios_config:
        lines:
          - no ip dhcp relay information option vpn
          - no ip dhcp relay information option
          - no ip dhcp compatibility suboption link-selection standard
          - no ip dhcp compatibility suboption server-override standard
      failed_when: false
#
    - name: CLEAR CONFIG L3_EDGE_VLAN_IPV4_IPV6 1
      cisco.ios.ios_config:
        lines:
          - "no interface Vlan{{ edge_vlan_id }}"
      failed_when: false
#
    - name: CLEAR CONFIG L3_EDGE_VLAN_IPV4_IPV6 2
      cisco.ios.ios_config:
        lines:
          - "no vlan {{ edge_vlan_id }}"
      failed_when: false
#
    - name: CLEAR CONFIG LEAF_CORE_VLAN_IPV4_IPV6
      cisco.ios.ios_config:
        lines:
          - "no vlan configuration {{ core_vlan_id }}"
          - "no vlan {{ core_vlan_id }}"
          - "no interface Vlan{{ core_vlan_id }}"
      failed_when: false
#
    - name: CLEAR CONFIG VRF
      cisco.ios.ios_config:
        lines:
          - "no vrf definition {{ vrf_name }}"
      failed_when: false
#
    - name: SHOW VRF
      cisco.ios.ios_command:
        commands:
          - show vrf
        wait_for:
          "result[0] not contains {{ vrf_name }}"
        retries: 999
      register: after_show_vrf
#
    - name: CLEAR CONFIG IPV6 ROUTING SUPPORT
      cisco.ios.ios_config:
        lines:
          - no ipv6 unicast-routing
      failed_when: false
#
...